"use strict";
exports.__esModule = true;
var value = "1";
console.log(typeof (value));
var value2 = value;
console.log(value2);
console.log(typeof (value2));
var value3 = value;
console.log(value3);
console.log(typeof (value3));
